Lmod has detected the following error: The following module(s) are unknown:
"Python/Python/3.7.4-GCCcore-8.3.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "Python/Python/3.7.4-GCCcore-8.3.0"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Requirement already up-to-date: pip==20.0.2 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (20.0.2)
WARNING: You are using pip version 20.0.2; however, version 20.3.3 is available.
You should consider upgrading via the '/data/s2964007/python_envs/python_envs/bin/python3 -m pip install --upgrade pip' command.
Requirement already up-to-date: setuptools==46.1.3 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (46.1.3)
WARNING: You are using pip version 20.0.2; however, version 20.3.3 is available.
You should consider upgrading via the '/data/s2964007/python_envs/python_envs/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: transformers in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (4.1.1)
Requirement already satisfied: packaging in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (20.8)
Requirement already satisfied: filelock in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (3.0.12)
Requirement already satisfied: sacremoses in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (0.0.43)
Requirement already satisfied: tqdm>=4.27 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (4.55.1)
Requirement already satisfied: tokenizers==0.9.4 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (0.9.4)
Requirement already satisfied: numpy in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (1.19.4)
Requirement already satisfied: dataclasses; python_version < "3.7" in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (0.8)
Requirement already satisfied: requests in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (2.25.1)
Requirement already satisfied: regex!=2019.12.17 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from transformers) (2020.11.13)
Requirement already satisfied: pyparsing>=2.0.2 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from packaging->transformers) (2.4.7)
Requirement already satisfied: six in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from sacremoses->transformers) (1.15.0)
Requirement already satisfied: click in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from sacremoses->transformers) (7.1.2)
Requirement already satisfied: joblib in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from sacremoses->transformers) (1.0.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests->transformers) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests->transformers) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests->transformers) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests->transformers) (2.10)
WARNING: You are using pip version 20.0.2; however, version 20.3.3 is available.
You should consider upgrading via the '/data/s2964007/python_envs/python_envs/bin/python3 -m pip install --upgrade pip' command.
Collecting datasets
  Using cached datasets-1.1.3-py3-none-any.whl (153 kB)
Requirement already satisfied: dataclasses; python_version < "3.7" in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from datasets) (0.8)
Requirement already satisfied: numpy>=1.17 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from datasets) (1.19.4)
Collecting dill
  Using cached dill-0.3.3-py2.py3-none-any.whl (81 kB)
Collecting multiprocess
  Downloading multiprocess-0.70.11.1-py36-none-any.whl (101 kB)
Collecting pandas
  Downloading pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5 MB)
Collecting pyarrow>=0.17.1
  Downloading pyarrow-2.0.0-cp36-cp36m-manylinux2014_x86_64.whl (17.7 MB)
Requirement already satisfied: requests>=2.19.0 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from datasets) (2.25.1)
Collecting xxhash
  Downloading xxhash-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl (242 kB)
Collecting tqdm<4.50.0,>=4.27
  Using cached tqdm-4.49.0-py2.py3-none-any.whl (69 kB)
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Downloading pytz-2020.5-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests>=2.19.0->datasets) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests>=2.19.0->datasets) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests>=2.19.0->datasets) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from requests>=2.19.0->datasets) (2.10)
Requirement already satisfied: six>=1.5 in /data/s2964007/python_envs/python_envs/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.15.0)
Installing collected packages: dill, multiprocess, python-dateutil, pytz, pandas, pyarrow, xxhash, tqdm, datasets
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.55.1
    Uninstalling tqdm-4.55.1:
      Successfully uninstalled tqdm-4.55.1
Successfully installed datasets-1.1.3 dill-0.3.3 multiprocess-0.70.11.1 pandas-1.1.5 pyarrow-2.0.0 python-dateutil-2.8.1 pytz-2020.5 tqdm-4.49.0 xxhash-2.0.0
WARNING: You are using pip version 20.0.2; however, version 20.3.3 is available.
You should consider upgrading via the '/data/s2964007/python_envs/python_envs/bin/python3 -m pip install --upgrade pip' command.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "run_mlm.py", line 49, in <module>
    MODEL_CONFIG_CLASSES = list(MODEL_FOR_MASKED_LM_MAPPING.keys())
AttributeError: 'NoneType' object has no attribute 'keys'


###############################################################################
Peregrine Cluster
Job 16570857 for user 's2964007'
Finished at: Mon Jan  4 12:07:29 CET 2021

Job details:
============

Job ID              : 16570857
Name                : BERT_Finetuning
User                : s2964007
Partition           : gpushort
Nodes               : pg-gpu33
Number of Nodes     : 1
Cores               : 12
State               : FAILED
Submit              : 2021-01-04T12:06:32
Start               : 2021-01-04T12:06:33
End                 : 2021-01-04T12:07:29
Reserved walltime   : 01:00:00
Used walltime       : 00:00:56
Used CPU time       : 00:00:16 (efficiency:  2.42%)
% User (Computation): 70.94%
% System (I/O)      : 29.05%
Mem reserved        : 4000M/node
Max Mem used        : 53.92M (pg-gpu33)
Max Disk Write      : 3.28M (pg-gpu33)
Max Disk Read       : 35.81M (pg-gpu33)


Acknowledgements:
=================

Please see this page for information about acknowledging Peregrine in your publications:

https://wiki.hpc.rug.nl/peregrine/introduction/scientific_output

################################################################################
