
The following have been reloaded with a version change:
  1) GCCcore/8.3.0 => GCCcore/9.3.0
  2) GMP/6.1.2-GCCcore-8.3.0 => GMP/6.2.0-GCCcore-9.3.0
  3) Python/3.7.4-GCCcore-8.3.0 => Python/3.8.2-GCCcore-9.3.0
  4) SQLite/3.29.0-GCCcore-8.3.0 => SQLite/3.31.1-GCCcore-9.3.0
  5) Tcl/8.6.9-GCCcore-8.3.0 => Tcl/8.6.10-GCCcore-9.3.0
  6) XZ/5.2.4-GCCcore-8.3.0 => XZ/5.2.5-GCCcore-9.3.0
  7) binutils/2.32-GCCcore-8.3.0 => binutils/2.34-GCCcore-9.3.0
  8) bzip2/1.0.8-GCCcore-8.3.0 => bzip2/1.0.8-GCCcore-9.3.0
  9) libffi/3.2.1-GCCcore-8.3.0 => libffi/3.3-GCCcore-9.3.0
 10) libreadline/8.0-GCCcore-8.3.0 => libreadline/8.0-GCCcore-9.3.0
 11) ncurses/6.1-GCCcore-8.3.0 => ncurses/6.2-GCCcore-9.3.0
 12) zlib/1.2.11-GCCcore-8.3.0 => zlib/1.2.11-GCCcore-9.3.0

Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Using cached pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
Successfully installed pip-20.3.1
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in /home/s2964007/.local/lib/python3.8/site-packages (4.0.0)
Requirement already satisfied: tokenizers==0.9.4 in /home/s2964007/.local/lib/python3.8/site-packages (from transformers) (0.9.4)
Requirement already satisfied: filelock in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from transformers) (3.0.12)
Requirement already satisfied: requests in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from transformers) (2.23.0)
Requirement already satisfied: numpy in /apps/skylake/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages (from transformers) (1.17.3)
Requirement already satisfied: sacremoses in /home/s2964007/.local/lib/python3.8/site-packages (from transformers) (0.0.43)
Requirement already satisfied: regex!=2019.12.17 in /home/s2964007/.local/lib/python3.8/site-packages (from transformers) (2020.11.13)
Requirement already satisfied: packaging in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from transformers) (20.3)
Requirement already satisfied: tqdm>=4.27 in /home/s2964007/.local/lib/python3.8/site-packages (from transformers) (4.49.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests->transformers) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests->transformers) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests->transformers) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: click in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from sacremoses->transformers) (7.1.1)
Requirement already satisfied: six in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from sacremoses->transformers) (1.14.0)
Requirement already satisfied: joblib in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from sacremoses->transformers) (0.14.1)
Requirement already satisfied: pyparsing>=2.0.2 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from packaging->transformers) (2.4.7)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /home/s2964007/.local/lib/python3.8/site-packages (1.1.3)
Requirement already satisfied: tqdm<4.50.0,>=4.27 in /home/s2964007/.local/lib/python3.8/site-packages (from datasets) (4.49.0)
Requirement already satisfied: dill in /home/s2964007/.local/lib/python3.8/site-packages (from datasets) (0.3.3)
Requirement already satisfied: multiprocess in /home/s2964007/.local/lib/python3.8/site-packages (from datasets) (0.70.11.1)
Requirement already satisfied: xxhash in /home/s2964007/.local/lib/python3.8/site-packages (from datasets) (2.0.0)
Requirement already satisfied: numpy>=1.17 in /apps/skylake/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages (from datasets) (1.17.3)
Requirement already satisfied: pyarrow>=0.17.1 in /home/s2964007/.local/lib/python3.8/site-packages (from datasets) (2.0.0)
Requirement already satisfied: requests>=2.19.0 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from datasets) (2.23.0)
Requirement already satisfied: pandas in /apps/skylake/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages (from datasets) (0.25.3)
Requirement already satisfied: certifi>=2017.4.17 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (1.25.9)
Requirement already satisfied: pytz>=2017.2 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from pandas->datasets) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from pandas->datasets) (2.8.1)
Requirement already satisfied: six>=1.5 in /apps/skylake/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas->datasets) (1.14.0)
Traceback (most recent call last):
  File "/software/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/software/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/software/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_mlm.py", line 30, in <module>
    from datasets import load_dataset
  File "/home/s2964007/.local/lib/python3.8/site-packages/datasets/__init__.py", line 23, in <module>
    import pyarrow
  File "/home/s2964007/.local/lib/python3.8/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/lib.pyx", line 24, in init pyarrow.lib
  File "/software/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/software/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/software/software/Python/3.8.2-GCCcore-9.3.0/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'



###############################################################################
Peregrine Cluster
Job 16142864 for user 's2964007'
Finished at: Sun Dec 13 18:36:59 CET 2020

Job details:
============

Job ID              : 16142864
Name                : BERT_Finetuning
User                : s2964007
Partition           : gpu
Nodes               : pg-gpu10
Number of Nodes     : 1
Cores               : 12
State               : FAILED
Submit              : 2020-12-13T18:21:19
Start               : 2020-12-13T18:36:20
End                 : 2020-12-13T18:36:59
Reserved walltime   : 01:00:00
Used walltime       : 00:00:39
Used CPU time       : 00:00:07 (efficiency:  1.66%)
% User (Computation): 71.67%
% System (I/O)      : 28.33%
Mem reserved        : 4000M/node
Max Mem used        : 40.05M (pg-gpu10)
Max Disk Write      : 81.92K (pg-gpu10)
Max Disk Read       : 1.28M (pg-gpu10)
Average GPU usage   : No GPU metrics available (pg-gpu10)


Acknowledgements:
=================

Please see this page for information about acknowledging Peregrine in your publications:

https://wiki.hpc.rug.nl/peregrine/additional_information/scientific_output

################################################################################
